CREATE DATABASE MeuBanco;

USE MeuBanco;

CREATE TABLE Cursos (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Descricao VARCHAR(255) NOT NULL
);

CREATE TABLE Leads (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Telefone VARCHAR(20) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    CursoInteresse INT NOT NULL,
    FOREIGN KEY (CursoInteresse) REFERENCES Cursos(Id)
);

CREATE TABLE Turmas (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Descricao VARCHAR(255) NOT NULL,
    CursoId INT NOT NULL,
    FOREIGN KEY (CursoId) REFERENCES Cursos(Id)
);

CREATE TABLE Alunos (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CodigoMatricula INT NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Telefone VARCHAR(20) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    CursoId INT NOT NULL,
    TurmaId INT NOT NULL,
    DataCadastro DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CursoId) REFERENCES Cursos(Id),
    FOREIGN KEY (TurmaId) REFERENCES Turmas(Id)
);
